title: LiRulei's Homepage
page-top-title: LiRulei - Geophysics
top-section-bg-text: 路漫漫其修远兮，吾将上下而求索。
home-subtitle: LiRulei&ensp;|&ensp;李如磊
PhD: Doctoral candidate at China University of Petroleum(Beijing), 2026 grade
copyright-text: '&copy; LiRulei 2026. All Rights Reserved.'
